### ISSUE TITLE
Program crashes when first name has a space in it.

### ISSUE THREAD

**Issue by ersan** [mwynholds/southy#2]
I'm trying to check someone in with a hyphenated first name, but Southwest would only allow me to put a space in the name instead of a hyphen.

When the app tries to check them in this happens:
```
ERROR  2016-03-16 09:15:47  Unexpected error
undefined method `group=' for nil:NilClass
Stacktrace:
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/monkey.rb:156:in `block in checkin'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/monkey.rb:154:in `map'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/monkey.rb:154:in `checkin'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/travel_agent.rb:38:in `checkin'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/daemon.rb:54:in `block in run'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/daemon.rb:50:in `each'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/daemon.rb:50:in `run'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/daemon.rb:24:in `start'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/service.rb:21:in `block in start'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/service.rb:21:in `fork'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/service.rb:21:in `start'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/lib/southy/cli.rb:20:in `start'
/home/ersan/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/southy-1.2/bin/southy:54:in `<top (required)>'
/home/ersan/.rbenv/versions/1.9.3-p448/bin/southy:23:in `load'
/home/ersan/.rbenv/versions/1.9.3-p448/bin/southy:23:in `<main>'

```

I'm not very well versed in Ruby or I could probably figure out how to fix it, so I'm hoping someone here can!

**Comment by ersan** [comment]
As of the latest commit it does this instead:
` INFO  2016-03-16 22:40:40  Unable to check in R2JTL5 for First name Lastname`
